- name: db
  hosts: db
  become: yes
  vars:
    login_host: db.sureshm.online
  vars_prompt:
    name: db_password
    prompt: enter db password
    private: no
  tasks:
  - name: mysql install
    dnf:
      name: mysql-server
      state: latest

  - name: install python mysql dependencies
    ansible.builtin.pip:
      name:
      - PyMySQL
      executable: pip3.9

  
  - name: start and enable mysqld
    service:
      name: mysqld
      state: started
      enabled: yes
  
  - name: check db connection
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ db_password }}"
      login_host: "{{ login_host }}"
      filter: version
    ignore_errors: yes
    register: output