- name: db
  hosts: db
  become: yes
  vars:
    login_host: db.sureshm.online
  vars_prompt:
    name: mysql_root_password
    prompt: enter Mysql root password
    private: no
  tasks:
  - name: mysql install
    dnf:
      name: mysql-server
      state: latest

  - name: install python mysql dependencies
    ansible.builtin.pip:
      name:
      - PyMySQL
      - cryptography
      executable: pip3.9

  - name: start and enable mysqld
    service:
      name: mysqld
      state: started
      enabled: yes
  
  # check password is already setup or not
  - name: check db connection
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"
      filter: version
    ignore_errors: yes
    register: mysql_connection_output

  - name: print output
    debug:
      msg: "output: {{ mysql_connection_output }}"

  - name: setup root password
    command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: mysql_connection_output.failed is true # don't give {{ }} in when condition